# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "vimperfect"
license = "MIT"
licenselink = "https://github.com/dotMavriQ/vimperfect/blob/master/LICENSE.md"
description = "Forked theme of Future Imperfect, which is a port of HTML5 UP, future imperfect, with some extra goodies"
homepage = "https://github.com/dotMavriQ/vimperfect"
tags = ["blog", "responsive", "font awesome", "highlight.js", "fancybox 3", "staticman", "netlify"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "dotMavriQ"
  homepage = "https://dotMavriQ.Life"

# If porting an existing theme
[original]
  name = "vimperfect"
  homepage = "https://github.com/dotMavriQ/vimperfect"
  repo = ""
